title: BAPAT
author: Michael Mulianto
email: michaelmulianto@gmail.com
description: > # this means to ignore newlines until "baseurl:"

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
